#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* OpenAPI spec version: 11.9.4
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/



@protocol PBAddress
@end

@interface PBAddress : PBObject


@property(nonatomic) NSString* objectId;

@property(nonatomic) NSString* displayName;

@property(nonatomic) NSString* streetSide;

@property(nonatomic) NSString* businessName;

@property(nonatomic) NSString* addressLine1;

@property(nonatomic) NSString* addressLine2;

@property(nonatomic) NSString* addressLine3;

@property(nonatomic) NSString* city;

@property(nonatomic) NSString* stateProvince;

@property(nonatomic) NSString* county;

@property(nonatomic) NSString* postalCode;

@property(nonatomic) NSString* latitude;

@property(nonatomic) NSString* longitude;

@property(nonatomic) NSString* status;

@property(nonatomic) NSString* urbanizationName;

@property(nonatomic) NSString* formattedAddress;

@property(nonatomic) NSString* mainAddressLine;

@property(nonatomic) NSString* addressLastLine;

@property(nonatomic) NSString* placeName;

@property(nonatomic) NSString* areaName1;

@property(nonatomic) NSString* areaName2;

@property(nonatomic) NSString* areaName3;

@property(nonatomic) NSString* areaName4;

@property(nonatomic) NSString* postCode;

@property(nonatomic) NSString* postCodeExt;

@property(nonatomic) NSString* country;

@property(nonatomic) NSString* addressNumber;

@property(nonatomic) NSString* streetName;

@property(nonatomic) NSString* unitType;

@property(nonatomic) NSString* unitValue;

@end
