#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 18.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol PBCategory
@end

@interface PBCategory : PBObject


@property(nonatomic) NSString* categoryCode;

@property(nonatomic) NSString* tradeDivision;

@property(nonatomic) NSString* tradeGroup;

@property(nonatomic) NSString* subClass;

@property(nonatomic) NSString* _class;

@end
