#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 12.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol PBCategoryMetadata
@end

@interface PBCategoryMetadata : PBObject


@property(nonatomic) NSString* code;

@property(nonatomic) NSString* sic;

@property(nonatomic) NSString* tradeDivision;

@property(nonatomic) NSString* tradeGroup;

@property(nonatomic) NSString* _class;

@property(nonatomic) NSString* subClass;

@property(nonatomic) NSString* _description;

@end
