#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 16.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBCbsa.h"
#import "PBMcd.h"
@protocol PBCbsa;
@class PBCbsa;
@protocol PBMcd;
@class PBMcd;



@protocol PBCensus
@end

@interface PBCensus : PBObject


@property(nonatomic) PBCbsa* cbsa;

@property(nonatomic) NSString* matchLevel;

@property(nonatomic) NSString* matchCode;

@property(nonatomic) NSString* tract;

@property(nonatomic) PBMcd* mcd;

@end
