#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 12.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBGeoLocationFixedLineCountry.h"
@protocol PBGeoLocationFixedLineCountry;
@class PBGeoLocationFixedLineCountry;



@protocol PBDeviceStatusNetwork
@end

@interface PBDeviceStatusNetwork : PBObject


@property(nonatomic) NSString* carrier;

@property(nonatomic) NSString* callType;

@property(nonatomic) NSString* locAccuracySupport;

@property(nonatomic) NSString* nationalNumber;

@property(nonatomic) PBGeoLocationFixedLineCountry* country;

@end
