#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 16.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBDemographicsAdvancedPreferences.h"
#import "PBDemographicsGeometry.h"
@protocol PBDemographicsAdvancedPreferences;
@class PBDemographicsAdvancedPreferences;
@protocol PBDemographicsGeometry;
@class PBDemographicsGeometry;



@protocol PBDemographicsAdvancedRequest
@end

@interface PBDemographicsAdvancedRequest : PBObject


@property(nonatomic) PBDemographicsAdvancedPreferences* preferences;

@property(nonatomic) PBDemographicsGeometry* geometry;

@property(nonatomic) NSString* geometryAsText;

@end
