#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 12.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBEventsCount.h"
#import "PBGrid.h"
#import "PBRiskAddress.h"
@protocol PBEventsCount;
@class PBEventsCount;
@protocol PBGrid;
@class PBGrid;
@protocol PBRiskAddress;
@class PBRiskAddress;



@protocol PBEarthquakeRiskResponse
@end

@interface PBEarthquakeRiskResponse : PBObject


@property(nonatomic) NSString* objectId;

@property(nonatomic) NSString* riskLevel;

@property(nonatomic) PBEventsCount* eventsCount;

@property(nonatomic) PBGrid* grid;

@property(nonatomic) PBRiskAddress* matchedAddress;

@end
