#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 17.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol PBEventsCount
@end

@interface PBEventsCount : PBObject


@property(nonatomic) NSString* total;

@property(nonatomic) NSString* r0;

@property(nonatomic) NSString* r1;

@property(nonatomic) NSString* r2;

@property(nonatomic) NSString* r3;

@property(nonatomic) NSString* r4;

@property(nonatomic) NSString* r5;

@property(nonatomic) NSString* r6;

@property(nonatomic) NSString* r7;

@property(nonatomic) NSString* r0Ge;

@property(nonatomic) NSString* r1Ge;

@property(nonatomic) NSString* r2Ge;

@property(nonatomic) NSString* r3Ge;

@property(nonatomic) NSString* r4Ge;

@property(nonatomic) NSString* r5Ge;

@property(nonatomic) NSString* r6Ge;

@property(nonatomic) NSString* r7Ge;

@end
