#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* OpenAPI spec version: 9.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/



@protocol PBEventsCount
@end

@interface PBEventsCount : PBObject


@property(nonatomic) NSString* total;

@property(nonatomic) NSString* r0;

@property(nonatomic) NSString* r1;

@property(nonatomic) NSString* r2;

@property(nonatomic) NSString* r3;

@property(nonatomic) NSString* r4;

@property(nonatomic) NSString* r5;

@property(nonatomic) NSString* r6;

@property(nonatomic) NSString* r7;

@property(nonatomic) NSString* r0Ge;

@property(nonatomic) NSString* r1Ge;

@property(nonatomic) NSString* r2Ge;

@property(nonatomic) NSString* r3Ge;

@property(nonatomic) NSString* r4Ge;

@property(nonatomic) NSString* r5Ge;

@property(nonatomic) NSString* r6Ge;

@property(nonatomic) NSString* r7Ge;

@end
