#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 18.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBAreaV2.h"
@protocol PBAreaV2;
@class PBAreaV2;



@protocol PBFireEventV2
@end

@interface PBFireEventV2 : PBObject


@property(nonatomic) NSString* fireStartDate;

@property(nonatomic) NSString* fireEndDate;

@property(nonatomic) NSString* fireName;

@property(nonatomic) PBAreaV2* area;

@property(nonatomic) NSString* agency;

@end
