#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 18.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBFireEventsV2Response.h"
@protocol PBFireEventsV2Response;
@class PBFireEventsV2Response;



@protocol PBFireHistoryV2
@end

@interface PBFireHistoryV2 : PBObject


@property(nonatomic) NSString* stateCode;

@property(nonatomic) NSString* postCode;

@property(nonatomic) PBFireEventsV2Response* events;

@end
