#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 14.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBFireEventsResponse.h"
@protocol PBFireEventsResponse;
@class PBFireEventsResponse;



@protocol PBFireHistory
@end

@interface PBFireHistory : PBObject


@property(nonatomic) NSString* stateCode;

@property(nonatomic) NSString* postCode;

@property(nonatomic) PBFireEventsResponse* events;

@end
