#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 17.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBFireEventV2.h"
@protocol PBFireEventV2;
@class PBFireEventV2;



@protocol PBFireEventsV2Response
@end

@interface PBFireEventsV2Response : PBObject


@property(nonatomic) NSArray<PBFireEventV2>* event;

@end
