#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 18.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol PBFormattedTaxAddress
@end

@interface PBFormattedTaxAddress : PBObject


@property(nonatomic) NSString* mainAddressLine;

@property(nonatomic) NSString* addressNumber;

@property(nonatomic) NSString* streetPreDirection;

@property(nonatomic) NSString* streetName;

@property(nonatomic) NSString* streetType;

@property(nonatomic) NSString* streetPostDirection;

@property(nonatomic) NSString* unitType;

@property(nonatomic) NSString* unitValue;

@property(nonatomic) NSString* city;

@property(nonatomic) NSString* state;

@property(nonatomic) NSString* postCode1;

@property(nonatomic) NSString* postCode2;

@end
