#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 17.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBCandidate.h"
@protocol PBCandidate;
@class PBCandidate;



@protocol PBGeocodeServiceResponse
@end

@interface PBGeocodeServiceResponse : PBObject


@property(nonatomic) NSString* objectId;

@property(nonatomic) NSNumber* totalPossibleCandidates;

@property(nonatomic) NSNumber* totalMatches;

@property(nonatomic) NSArray<PBCandidate>* candidates;

@end
