#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 16.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol PBGradeLevelsTaught
@end

@interface PBGradeLevelsTaught : PBObject


@property(nonatomic) NSString* pk;

@property(nonatomic) NSString* kg;

@property(nonatomic) NSString* first;

@property(nonatomic) NSString* second;

@property(nonatomic) NSString* third;

@property(nonatomic) NSString* fourth;

@property(nonatomic) NSString* fifth;

@property(nonatomic) NSString* sixth;

@property(nonatomic) NSString* seventh;

@property(nonatomic) NSString* eighth;

@property(nonatomic) NSString* ninth;

@property(nonatomic) NSString* tenth;

@property(nonatomic) NSString* eleventh;

@property(nonatomic) NSString* twelfth;

@end
