#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 18.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBAddress1.h"
#import "PBIntersection.h"
@protocol PBAddress1;
@class PBAddress1;
@protocol PBIntersection;
@class PBIntersection;



@protocol PBIntersectionResponse
@end

@interface PBIntersectionResponse : PBObject


@property(nonatomic) NSArray<PBIntersection>* intersection;

@property(nonatomic) PBAddress1* matchedAddress;

@end
