#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 16.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBLocalTaxPreferences.h"
#import "PBTaxRateMatchedAddress.h"
@protocol PBLocalTaxPreferences;
@class PBLocalTaxPreferences;
@protocol PBTaxRateMatchedAddress;
@class PBTaxRateMatchedAddress;



@protocol PBIPDTaxByAddressBatchRequest
@end

@interface PBIPDTaxByAddressBatchRequest : PBObject


@property(nonatomic) NSArray<PBTaxRateMatchedAddress>* addresses;

@property(nonatomic) PBLocalTaxPreferences* preferences;

@end
