#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 17.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol PBMatch
@end

@interface PBMatch : PBObject


@property(nonatomic) NSString* confidence;

@property(nonatomic) NSString* percentGeocode;

@property(nonatomic) NSString* precisionLevel;

@property(nonatomic) NSString* locationCode;

@property(nonatomic) NSString* matchCode;

@end
