#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 16.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol PBMagnitude
@end

@interface PBMagnitude : PBObject


@property(nonatomic) NSNumber* value;

@property(nonatomic) NSString* scale;

@property(nonatomic) NSNumber* bodyWave;

@property(nonatomic) NSNumber* surfaceWave;

@property(nonatomic) NSNumber* surfaceWaveValue;

@property(nonatomic) NSNumber* bodyWaveValue;

@end
