#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 16.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol PBMatchedAddress
@end

@interface PBMatchedAddress : PBObject


@property(nonatomic) NSString* objectId;

@property(nonatomic) NSString* displayName;

@property(nonatomic) NSString* streetSide;

@property(nonatomic) NSString* businessName;

@property(nonatomic) NSString* addressLine1;

@property(nonatomic) NSString* addressLine2;

@property(nonatomic) NSString* addressLine3;

@property(nonatomic) NSString* city;

@property(nonatomic) NSString* stateProvince;

@property(nonatomic) NSString* county;

@property(nonatomic) NSString* postalCode;

@property(nonatomic) NSString* latitude;

@property(nonatomic) NSString* longitude;

@property(nonatomic) NSString* status;

@property(nonatomic) NSString* urbanizationName;

@property(nonatomic) NSString* formattedAddress;

@property(nonatomic) NSString* mainAddressLine;

@property(nonatomic) NSString* addressLastLine;

@property(nonatomic) NSString* placeName;

@property(nonatomic) NSString* areaName1;

@property(nonatomic) NSString* areaName2;

@property(nonatomic) NSString* areaName3;

@property(nonatomic) NSString* areaName4;

@property(nonatomic) NSString* postCode;

@property(nonatomic) NSString* postCodeExt;

@property(nonatomic) NSString* country;

@property(nonatomic) NSString* addressNumber;

@property(nonatomic) NSString* streetName;

@property(nonatomic) NSString* unitType;

@property(nonatomic) NSString* unitValue;

@end
