#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* OpenAPI spec version: 11.9.4
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

#import "PBCenter.h"
#import "PBCommonGeometry.h"
#import "PBMatchedAddress.h"
#import "PBParcel.h"
#import "PBParcelBoundary.h"


@protocol PBParcelBoundary
@end

@interface PBParcelBoundary : PBObject


@property(nonatomic) NSString* objectId;

@property(nonatomic) NSString* apn;

@property(nonatomic) NSString* pid;

@property(nonatomic) PBCenter* center;

@property(nonatomic) NSString* countyfips;

@property(nonatomic) PBCommonGeometry* geometry;

@property(nonatomic) NSArray<PBParcel>* parcelList;

@property(nonatomic) NSArray<PBParcelBoundary>* adjacentParcelBoundary;

@property(nonatomic) PBMatchedAddress* matchedAddress;

@end
