#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 11.9.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBCenter.h"
#import "PBMatchedAddress.h"
#import "PBParcel.h"
#import "PBParcelBoundary.h"
#import "PBPropertyInformationGeometry.h"
@protocol PBCenter;
@class PBCenter;
@protocol PBMatchedAddress;
@class PBMatchedAddress;
@protocol PBParcel;
@class PBParcel;
@protocol PBParcelBoundary;
@class PBParcelBoundary;
@protocol PBPropertyInformationGeometry;
@class PBPropertyInformationGeometry;



@protocol PBParcelBoundary
@end

@interface PBParcelBoundary : PBObject


@property(nonatomic) NSString* objectId;

@property(nonatomic) NSString* apn;

@property(nonatomic) NSString* pid;

@property(nonatomic) PBCenter* center;

@property(nonatomic) NSString* countyfips;

@property(nonatomic) PBPropertyInformationGeometry* geometry;

@property(nonatomic) NSArray<PBParcel>* parcelList;

@property(nonatomic) NSArray<PBParcelBoundary>* adjacentParcelBoundary;

@property(nonatomic) PBMatchedAddress* matchedAddress;

@end
