#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 17.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBCenter.h"
#import "PBMatchedAddress.h"
#import "PBParcelBoundaryV2.h"
#import "PBParcelV2.h"
#import "PBPropertyInformationGeometry.h"
@protocol PBCenter;
@class PBCenter;
@protocol PBMatchedAddress;
@class PBMatchedAddress;
@protocol PBParcelBoundaryV2;
@class PBParcelBoundaryV2;
@protocol PBParcelV2;
@class PBParcelV2;
@protocol PBPropertyInformationGeometry;
@class PBPropertyInformationGeometry;



@protocol PBParcelBoundaryV2
@end

@interface PBParcelBoundaryV2 : PBObject


@property(nonatomic) NSString* objectId;

@property(nonatomic) NSString* parcelApn;

@property(nonatomic) NSString* geoId;

@property(nonatomic) PBCenter* center;

@property(nonatomic) NSString* countyfips;

@property(nonatomic) NSString* parcelAreaSqFt;

@property(nonatomic) PBPropertyInformationGeometry* geometry;

@property(nonatomic) NSArray<PBParcelV2>* parcelList;

@property(nonatomic) NSArray<PBParcelBoundaryV2>* adjacentParcelBoundary;

@property(nonatomic) PBMatchedAddress* matchedAddress;

@end
