#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 11.9.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol PBProxy
@end

@interface PBProxy : PBObject


@property(nonatomic) NSString* anonymizerStatus;

@property(nonatomic) NSString* level;

@property(nonatomic) NSString* lastDetected;

@property(nonatomic) NSString* type;

@end
