#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 16.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBMatchedAddress.h"
#import "PBPropertyAttributes.h"
@protocol PBMatchedAddress;
@class PBMatchedAddress;
@protocol PBPropertyAttributes;
@class PBPropertyAttributes;



@protocol PBPropertyInfoResponse
@end

@interface PBPropertyInfoResponse : PBObject


@property(nonatomic) NSString* objectId;

@property(nonatomic) PBPropertyAttributes* propertyAttributes;

@property(nonatomic) PBMatchedAddress* matchedAddress;

@end
