#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 11.9.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBAbsenteeOwner.h"
#import "PBBasementType.h"
#import "PBBuildgCondition.h"
#import "PBBuildgFeaturesSqft.h"
#import "PBBuildgStyle.h"
#import "PBBuildgType.h"
#import "PBBuildingSqftSource.h"
#import "PBCaExemptions.h"
#import "PBConstruction.h"
#import "PBCoolingType.h"
#import "PBExteriorWalls.h"
#import "PBFoundation.h"
#import "PBGarageType.h"
#import "PBHeatingType.h"
#import "PBLandUse.h"
#import "PBOwners.h"
#import "PBPropertyGeometry.h"
#import "PBRoofCoverType.h"
#import "PBRoofFrameType.h"
#import "PBRoofShapeType.h"
#import "PBStories.h"
#import "PBTaxExemption.h"
#import "PBVacancy.h"
@protocol PBAbsenteeOwner;
@class PBAbsenteeOwner;
@protocol PBBasementType;
@class PBBasementType;
@protocol PBBuildgCondition;
@class PBBuildgCondition;
@protocol PBBuildgFeaturesSqft;
@class PBBuildgFeaturesSqft;
@protocol PBBuildgStyle;
@class PBBuildgStyle;
@protocol PBBuildgType;
@class PBBuildgType;
@protocol PBBuildingSqftSource;
@class PBBuildingSqftSource;
@protocol PBCaExemptions;
@class PBCaExemptions;
@protocol PBConstruction;
@class PBConstruction;
@protocol PBCoolingType;
@class PBCoolingType;
@protocol PBExteriorWalls;
@class PBExteriorWalls;
@protocol PBFoundation;
@class PBFoundation;
@protocol PBGarageType;
@class PBGarageType;
@protocol PBHeatingType;
@class PBHeatingType;
@protocol PBLandUse;
@class PBLandUse;
@protocol PBOwners;
@class PBOwners;
@protocol PBPropertyGeometry;
@class PBPropertyGeometry;
@protocol PBRoofCoverType;
@class PBRoofCoverType;
@protocol PBRoofFrameType;
@class PBRoofFrameType;
@protocol PBRoofShapeType;
@class PBRoofShapeType;
@protocol PBStories;
@class PBStories;
@protocol PBTaxExemption;
@class PBTaxExemption;
@protocol PBVacancy;
@class PBVacancy;



@protocol PBPropertyAttributes
@end

@interface PBPropertyAttributes : PBObject


@property(nonatomic) NSString* pbKey;

@property(nonatomic) NSString* propApn;

@property(nonatomic) NSString* propType;

@property(nonatomic) NSString* propSqFt;

@property(nonatomic) NSString* buildgSqFt;

@property(nonatomic) PBBuildingSqftSource* buildgSqFtSource;

@property(nonatomic) PBLandUse* landUse;

@property(nonatomic) PBConstruction* construction;

@property(nonatomic) PBRoofCoverType* roofCoverType;

@property(nonatomic) NSString* subdivision;

@property(nonatomic) PBPropertyGeometry* geometry;

@property(nonatomic) NSString* builtYear;

@property(nonatomic) NSString* bedrooms;

@property(nonatomic) NSString* baths;

@property(nonatomic) NSString* pool;

@property(nonatomic) NSString* fireplace;

@property(nonatomic) NSString* mobileHome;

@property(nonatomic) PBHeatingType* heatingType;

@property(nonatomic) PBCoolingType* coolingType;

@property(nonatomic) NSString* assessedValue;

@property(nonatomic) NSString* marketValue;

@property(nonatomic) NSString* appraisedValue;

@property(nonatomic) NSString* taxAmount;

@property(nonatomic) NSArray<PBTaxExemption>* taxExemptions;

@property(nonatomic) PBCaExemptions* caExemptions;

@property(nonatomic) NSString* salesDate;

@property(nonatomic) NSString* priorSaleDate;

@property(nonatomic) NSString* priorSalesPrice;

@property(nonatomic) PBStories* stories;

@property(nonatomic) NSString* livingSqFt;

@property(nonatomic) PBRoofFrameType* roofFrameType;

@property(nonatomic) PBFoundation* foundation;

@property(nonatomic) PBBuildgCondition* buildgCondition;

@property(nonatomic) NSString* buildgCount;

@property(nonatomic) NSString* buildgUnitNo;

@property(nonatomic) NSArray<PBBuildgFeaturesSqft>* buildgFeaturesSqFt;

@property(nonatomic) NSString* businessName;

@property(nonatomic) NSString* taxAddress;

@property(nonatomic) PBVacancy* vacancy;

@property(nonatomic) NSArray<PBOwners>* owners;

@property(nonatomic) NSString* appraisedValueImp;

@property(nonatomic) NSString* assessedValueImp;

@property(nonatomic) PBBuildgType* buildgType;

@property(nonatomic) PBBasementType* basementType;

@property(nonatomic) NSString* effectiveBuiltYear;

@property(nonatomic) PBExteriorWalls* exteriorWalls;

@property(nonatomic) PBGarageType* garageType;

@property(nonatomic) NSString* lastUpdated;

@property(nonatomic) NSString* marketValueImp;

@property(nonatomic) PBAbsenteeOwner* absenteeOwner;

@property(nonatomic) NSString* parkingSqFt;

@property(nonatomic) NSString* replacementCost;

@property(nonatomic) PBRoofShapeType* roofShapeType;

@property(nonatomic) PBBuildgStyle* buildgStyle;

@property(nonatomic) NSString* basementSqFt;

@end
