#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 18.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBAHJmailingAddress.h"
#import "PBContactPerson.h"
#import "PBCounty.h"
#import "PBCoverage.h"
#import "PBSiteDetails.h"
@protocol PBAHJmailingAddress;
@class PBAHJmailingAddress;
@protocol PBContactPerson;
@class PBContactPerson;
@protocol PBCounty;
@class PBCounty;
@protocol PBCoverage;
@class PBCoverage;
@protocol PBSiteDetails;
@class PBSiteDetails;



@protocol PBPSAPResponse
@end

@interface PBPSAPResponse : PBObject


@property(nonatomic) NSString* psapId;

@property(nonatomic) NSString* fccId;

@property(nonatomic) NSString* type;

@property(nonatomic) NSNumber* count;

@property(nonatomic) NSString* agency;

@property(nonatomic) NSString* phone;

@property(nonatomic) PBCounty* county;

@property(nonatomic) PBCoverage* coverage;

@property(nonatomic) PBContactPerson* contactPerson;

@property(nonatomic) PBSiteDetails* siteDetails;

@property(nonatomic) PBAHJmailingAddress* mailingAddress;

@end
