#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 12.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBField.h"
@protocol PBField;
@class PBField;



@protocol PBRangeVariable
@end

@interface PBRangeVariable : PBObject


@property(nonatomic) NSString* count;

@property(nonatomic) NSString* order;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* alias;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSString* baseVariable;

@property(nonatomic) NSString* year;

@property(nonatomic) NSArray<PBField>* field;

@end
