#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 16.0.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol PBRiskPreferences
@end

@interface PBRiskPreferences : PBObject


@property(nonatomic) NSString* includeGeometry;

@property(nonatomic) NSString* includeZoneDesc;

@property(nonatomic) NSString* richterValue;

@end
