#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 15.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol PBSchoolDistrict
@end

@interface PBSchoolDistrict : PBObject


@property(nonatomic) NSString* ncesDistrictId;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* totalSchools;

@property(nonatomic) NSString* districtType;

@property(nonatomic) NSString* metro;

@property(nonatomic) NSString* areaInSqM;

@property(nonatomic) NSString* supervisoryUnionId;

@property(nonatomic) NSString* districtEnrollment;

@property(nonatomic) NSString* districtUrl;

@end
