#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 16.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol PBStudentEthnicity
@end

@interface PBStudentEthnicity : PBObject


@property(nonatomic) NSString* indianAlaskaNative;

@property(nonatomic) NSString* asian;

@property(nonatomic) NSString* hispanic;

@property(nonatomic) NSString* black;

@property(nonatomic) NSString* white;

@property(nonatomic) NSString* hawaiianPacificlslander;

@property(nonatomic) NSString* twoOrMoreRaces;

@end
