#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 18.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBTravelBoundary.h"
@protocol PBTravelBoundary;
@class PBTravelBoundary;



@protocol PBTravelBoundaries
@end

@interface PBTravelBoundaries : PBObject


@property(nonatomic) PBTravelBoundary* travelBoundary;

@end
