#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 18.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBAddress2.h"
#import "PBDistance1.h"
#import "PBGeometry.h"
#import "PBMatch1.h"
#import "PBPlace1.h"
#import "PBPoi.h"
#import "PBTypeaheadRange.h"
@protocol PBAddress2;
@class PBAddress2;
@protocol PBDistance1;
@class PBDistance1;
@protocol PBGeometry;
@class PBGeometry;
@protocol PBMatch1;
@class PBMatch1;
@protocol PBPlace1;
@class PBPlace1;
@protocol PBPoi;
@class PBPoi;
@protocol PBTypeaheadRange;
@class PBTypeaheadRange;



@protocol PBTypeaheadLocation
@end

@interface PBTypeaheadLocation : PBObject


@property(nonatomic) NSString* dataset;

@property(nonatomic) PBMatch1* match;

@property(nonatomic) PBAddress2* address;

@property(nonatomic) PBPoi* poi;

@property(nonatomic) PBDistance1* distance;

@property(nonatomic) NSString* unitTemp;

@property(nonatomic) NSString* valueTemp;

@property(nonatomic) PBGeometry* geometry;

@property(nonatomic) NSNumber* totalUnitCount;

@property(nonatomic) NSArray<PBTypeaheadRange>* ranges;

@property(nonatomic) PBPlace1* place;

@end
