#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 16.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBGetPostalCodesAPIOutputUserFields.h"
@protocol PBGetPostalCodesAPIOutputUserFields;
@class PBGetPostalCodesAPIOutputUserFields;



@protocol PBValidateMailingAddressProOutput
@end

@interface PBValidateMailingAddressProOutput : PBObject

/* These fields are returned, unmodified, in the user_fields section of the response. [optional]
 */
@property(nonatomic) NSArray<PBGetPostalCodesAPIOutputUserFields>* userFields;
/* The first line of the validated address. [optional]
 */
@property(nonatomic) NSString* addressLine1;
/* The second line of the validated address. [optional]
 */
@property(nonatomic) NSString* addressLine2;
/* The validated firm or company name. [optional]
 */
@property(nonatomic) NSString* firmName;
/* A value of 0 and 100 that reflects how much the address has changed to make it valid. [optional]
 */
@property(nonatomic) NSString* changeScore;
/* Generally a locality is a village in rural areas or it may be a suburb in urban areas. [optional]
 */
@property(nonatomic) NSString* locality;
/* The suburb name. [optional]
 */
@property(nonatomic) NSString* suburb;
/* A single letter code that indicates the type of address. [optional]
 */
@property(nonatomic) NSString* addressType;
/* An estimate of confidence that an item mailed or shipped to this address would be successfully delivered. [optional]
 */
@property(nonatomic) NSString* deliverability;
/* A two character code indicating overall quality of the resulting address. [optional]
 */
@property(nonatomic) NSString* addressQuality;
/* Mentions the address component that could not be validated, in case no match is found. [optional]
 */
@property(nonatomic) NSString* couldNotValidate;
/* The validated city name. [optional]
 */
@property(nonatomic) NSString* city;
/* The validated ZIP Code or postal code. [optional]
 */
@property(nonatomic) NSString* postalCode;
/* The country in the format determined by what you selected. [optional]
 */
@property(nonatomic) NSString* country;
/* The validated state or province abbreviation. [optional]
 */
@property(nonatomic) NSString* stateProvince;
/* The formatted address, as it would appear on a physical mail piece. [optional]
 */
@property(nonatomic) NSString* blockAddress;
/* Input data that could not be matched to a particular address component. [optional]
 */
@property(nonatomic) NSString* additionalInputData;
/* The 5-digit ZIP Code. [optional]
 */
@property(nonatomic) NSString* postalCodeBase;
/* The 4-digit add-on part of the ZIP Code. [optional]
 */
@property(nonatomic) NSString* postalCodeAddOn;
/* Reports the success or failure of the match attempt. [optional]
 */
@property(nonatomic) NSString* status;
/* Reason for failure, if there is one. [optional]
 */
@property(nonatomic) NSString* statusCode;
/* Description of the problem, if there is one. [optional]
 */
@property(nonatomic) NSString* statusDescription;

@end
