#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 18.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol PBValidateMailingAddressProOptions
@end

@interface PBValidateMailingAddressProOptions : PBObject

/* Specifies whether to return a formatted version of the address as it would be printed on a physical mail piece. [optional]
 */
@property(nonatomic) NSString* outputAddressBlocks;
/* Specifies whether to return multiple address for those input addresses that have more than one possible match. [optional]
 */
@property(nonatomic) NSString* keepMultimatch;
/* Specifies the format to use for the country name returned in the Country output field. [optional]
 */
@property(nonatomic) NSString* outputCountryFormat;
/* Specifies the alphabet or script in which the output should be returned. [optional]
 */
@property(nonatomic) NSString* outputScript;
/* Specify the casing of the output data. [optional]
 */
@property(nonatomic) NSString* outputCasing;
/* A number between 1 and 10 that indicates the maximum number of addresses to return. [optional]
 */
@property(nonatomic) NSString* maximumResults;

@end
