#import <Foundation/Foundation.h>
#import "PBObject.h"

/**
* Precisely APIs
* Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
*
* The version of the OpenAPI document: 16.0.3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "PBCategory.h"
#import "PBZonesSic.h"
@protocol PBCategory;
@class PBCategory;
@protocol PBZonesSic;
@class PBZonesSic;



@protocol PBZonesPoiClassification
@end

@interface PBZonesPoiClassification : PBObject


@property(nonatomic) PBZonesSic* sic;

@property(nonatomic) PBCategory* category;

@property(nonatomic) NSString* alternateIndustryCode;

@end
